version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=stream
    ports:
      - '5432:5432'
